# Generated by Django 3.0.4 on 2020-03-15 17:04

from django.db import migrations, models
import django.db.models.deletion
import fitclip.mall.models.product.product_detail


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='제품을 분류할 카테고리 이름입니다.', max_length=10, verbose_name='대분류 이름')),
                ('icon_img', models.ImageField(default='/image/category/default.png', help_text='카테고리를 표현할 간단한 이미지입니다.', upload_to='', verbose_name='대분류 이미지')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='제품의 이름입니다.', max_length=50, verbose_name='제품 이름')),
                ('url', models.URLField(help_text='해당 제품으로 넘어가는 링크입니다.', null=True, verbose_name='제품 url')),
                ('price', models.IntegerField(help_text='제품의 가격입니다.', verbose_name='제품 가격')),
                ('category', models.ForeignKey(help_text='해당 제품의 카테고리입니다.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mall.Category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '제품',
                'verbose_name_plural': '제품',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='카테고리내의 상세 분류 이름입니다.', max_length=10, verbose_name='상세 분류 이름')),
                ('icon_img', models.ImageField(default='/image/section/default.png', help_text='상세 분류를 표현할 간단한 이미지입니다.', upload_to='', verbose_name='상세 분류 이미지')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '상세 분류',
                'verbose_name_plural': '상세 분류',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='쇼핑몰의 이름입니다.', max_length=50, verbose_name='쇼핑몰 이름')),
                ('url', models.URLField(help_text='쇼핑몰의 링크입니다.', null=True, verbose_name='쇼핑몰 url')),
                ('logo_img', models.ImageField(default='/image/mall/default.png', help_text='쇼핑몰의 대표 이미지입니다.', upload_to='', verbose_name='쇼핑몰 로고 이미지')),
            ],
            options={
                'verbose_name': '쇼핑몰',
                'verbose_name_plural': '쇼핑몰',
            },
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='상세 분류내의 특징적인 분류 이름입니다.', max_length=10, verbose_name='특징 분류 이름')),
                ('fit_specs', models.ManyToManyField(help_text='입력 받아야 할 특징 치수 데이터들의 모음입니다.', through='fit.FitSpecOption', to='fit.FitSpec', verbose_name='특징 치수 데이터 모음')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Section', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '특징 분류',
                'verbose_name_plural': '특징 분류',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='제품의 디테일 페이지에 표시될 상세 설명입니다.', verbose_name='제품 상세 설명')),
                ('thumbnail', models.ImageField(default='/image/product/default.png', help_text='제품의 대표 이미지입니다.', upload_to=fitclip.mall.models.product.product_detail.PathAndRename('/image/product/'), verbose_name='대표 이미지')),
                ('img_1', models.ImageField(blank=True, help_text='제품의 디테일 페이지에 표시될 이미지입니다.', null=True, upload_to=fitclip.mall.models.product.product_detail.PathAndRename('/image/product/'), verbose_name='이미지 01')),
                ('img_2', models.ImageField(blank=True, help_text='제품의 디테일 페이지에 표시될 이미지입니다.', null=True, upload_to=fitclip.mall.models.product.product_detail.PathAndRename('/image/product/'), verbose_name='이미지 02')),
                ('img_3', models.ImageField(blank=True, help_text='제품의 디테일 페이지에 표시될 이미지입니다.', null=True, upload_to=fitclip.mall.models.product.product_detail.PathAndRename('/image/product/'), verbose_name='이미지 03')),
                ('img_4', models.ImageField(blank=True, help_text='제품의 디테일 페이지에 표시될 이미지입니다.', null=True, upload_to=fitclip.mall.models.product.product_detail.PathAndRename('/image/product/'), verbose_name='이미지 04')),
                ('img_5', models.ImageField(blank=True, help_text='제품의 디테일 페이지에 표시될 이미지입니다.', null=True, upload_to=fitclip.mall.models.product.product_detail.PathAndRename('/image/product/'), verbose_name='이미지 05')),
                ('_meta_data', models.TextField(blank=True, help_text='json format의 메타데이터입니다.', null=True, verbose_name='메타데이터')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='mall.Product', verbose_name='제품')),
            ],
            options={
                'verbose_name': '제품 상세 정보',
                'verbose_name_plural': '제품 상세 정보',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.ForeignKey(help_text='해당 제품의 상세 분류입니다.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mall.Section', verbose_name='상세 분류'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(help_text='해당 제품을 판매하는 쇼핑몰입니다.', on_delete=django.db.models.deletion.CASCADE, to='mall.Shop', verbose_name='쇼핑몰'),
        ),
    ]
