# Generated by Django 3.0.4 on 2020-04-11 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Section', verbose_name='상세 분류'),
        ),
    ]
