# Generated by Django 3.0.1 on 2020-02-01 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='제품을 분류할 카테고리 이름입니다.', max_length=10, verbose_name='대분류 이름')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='제품의 이름입니다.', max_length=50, verbose_name='제품 이름')),
                ('price', models.IntegerField(help_text='제품의 가격입니다.', verbose_name='제품 가격')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '제품',
                'verbose_name_plural': '제품',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='쇼핑몰의 이름입니다.', max_length=50, verbose_name='쇼핑몰 이름')),
            ],
            options={
                'verbose_name': '쇼핑몰',
                'verbose_name_plural': '쇼핑몰',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='카테고리내의 상세 분류 이름입니다.', max_length=10, verbose_name='상세 분류 이름')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '상세 분류',
                'verbose_name_plural': '상세 분류',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='제품의 디테일 페이지에 표시될 상세 설명입니다.', verbose_name='제품 상세 설명')),
                ('thumbnail', models.ImageField(default='/static/product/default.png', help_text='제품의 대표 이미지입니다.', upload_to='', verbose_name='대표 이미지')),
                ('img_1', models.ImageField(blank=True, help_text='제품의 디테일 페이지에 표시될 이미지입니다.', null=True, upload_to='', verbose_name='이미지 01')),
                ('img_2', models.ImageField(blank=True, help_text='제품의 디테일 페이지에 표시될 이미지입니다.', null=True, upload_to='', verbose_name='이미지 02')),
                ('img_3', models.ImageField(blank=True, help_text='제품의 디테일 페이지에 표시될 이미지입니다.', null=True, upload_to='', verbose_name='이미지 03')),
                ('img_4', models.ImageField(blank=True, help_text='제품의 디테일 페이지에 표시될 이미지입니다.', null=True, upload_to='', verbose_name='이미지 04')),
                ('img_5', models.ImageField(blank=True, help_text='제품의 디테일 페이지에 표시될 이미지입니다.', null=True, upload_to='', verbose_name='이미지 05')),
                ('_meta_data', models.TextField(blank=True, help_text='json format의 메타데이터입니다.', null=True, verbose_name='메타데이터')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='shop.Product', verbose_name='제품')),
            ],
            options={
                'verbose_name': '제품 상세 정보',
                'verbose_name_plural': '제품 상세 정보',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Section', verbose_name='상세 분류'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop', verbose_name='쇼핑몰'),
        ),
    ]
