# Generated by Django 3.0.1 on 2020-02-02 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(help_text='해당 제품으로 넘어가는 링크입니다.', null=True, verbose_name='제품 url'),
        ),
        migrations.AddField(
            model_name='shop',
            name='logo_img',
            field=models.ImageField(default='/static/shop/default.png', help_text='쇼핑몰의 대표 이미지입니다.', upload_to='', verbose_name='쇼핑몰 로고 이미지'),
        ),
        migrations.AddField(
            model_name='shop',
            name='url',
            field=models.URLField(help_text='쇼핑몰의 링크입니다.', null=True, verbose_name='쇼핑몰 url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='해당 제품의 카테고리입니다.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Category', verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.ForeignKey(help_text='해당 제품의 상세 분류입니다.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Section', verbose_name='상세 분류'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(help_text='해당 제품을 판매하는 쇼핑몰입니다.', on_delete=django.db.models.deletion.CASCADE, to='shop.Shop', verbose_name='쇼핑몰'),
        ),
    ]
