# Generated by Django 3.0.4 on 2020-03-15 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='치수 데이터 이름')),
                ('fit_spec_type', models.CharField(choices=[('STR', '문자열'), ('NUM', '숫자')], default='STR', help_text='치수 데이터를 입력받을 데이터 타입입니다.', max_length=3, verbose_name='치수 데이터 타입')),
            ],
            options={
                'verbose_name': '치수 데이터',
                'verbose_name_plural': '치수 데이터',
            },
        ),
        migrations.CreateModel(
            name='FitSpecOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False, help_text='필수로 입력 받아야 하는 데이터 일 경우 True를 입력하세요.', verbose_name='필수 입력')),
                ('fit_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.FitSpec', verbose_name='치수 데이터')),
            ],
        ),
    ]
