# Generated by Django 3.0.4 on 2020-03-15 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fit', '0001_initial'),
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitspecoption',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Sub', verbose_name='특징 분류'),
        ),
    ]
