# Generated by Django 3.0.4 on 2020-04-11 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_auto_20200411_1616'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fit', '0002_fitspecoption_sub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitspecoption',
            options={'verbose_name': '특징 치수 데이터', 'verbose_name_plural': '특징 치수 데이터'},
        ),
        migrations.AlterField(
            model_name='fitspecoption',
            name='is_required',
            field=models.BooleanField(default=False, help_text='필수로 입력 받아야 하는 데이터 일 경우 선택하세요.', verbose_name='필수 입력'),
        ),
        migrations.CreateModel(
            name='FitStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='사용자가 입력한 제품 이름', max_length=20, verbose_name='제품 이름')),
                ('product_img', models.ImageField(help_text='사용자가 첨부한 제품의 사진', upload_to='', verbose_name='제품 사진')),
                ('raw_fit_specs', models.TextField(help_text='사용자가 입력한 raw 한 치수 데이터', verbose_name='raw 치수 데이터')),
                ('sub', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mall.Sub', verbose_name='특징 분류')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fits', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '입력 받은 치수 데이터',
                'verbose_name_plural': '입력 받은 치수 데이터들',
            },
        ),
    ]
