# Generated by Django 3.0.4 on 2020-04-11 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_auto_20200411_1616'),
        ('fit', '0003_auto_20200411_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalFit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='개인화 치수 데이터 이름')),
                ('personal_fit_type', models.CharField(choices=[('FLT', '실수형'), ('INT', '정수형')], default='FLT', help_text='치수 데이터를 입력받을 데이터 타입입니다.', max_length=3, verbose_name='개인화 치수 타입')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalFitUIOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_fit_ui_type', models.CharField(choices=[('SLD', '슬라이드'), ('BTN', '버튼')], default='SLD', help_text='개인화 치수 데이터를 표현 할 UI 타입입니다.', max_length=3, verbose_name='개인화 치수 UI 타입')),
                ('button_group', models.CharField(help_text='버튼을 하나의 그룹으로 묶을 이름입니다.', max_length=20, null=True, verbose_name='버튼 그룹')),
                ('personal_fit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit.PersonalFit', verbose_name='개인화 치수 데이터')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Sub', verbose_name='특징 분류')),
            ],
            options={
                'verbose_name': '개인화 치수 데이터',
                'verbose_name_plural': '개인화 치수 데이터들',
            },
        ),
    ]
