# Generated by Django 3.0.4 on 2020-04-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0004_personalfit_personalfituioption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitstore',
            options={'verbose_name': '입력 받은 치수 데이터', 'verbose_name_plural': '입력 받은 치수 데이터'},
        ),
        migrations.AlterModelOptions(
            name='personalfit',
            options={'verbose_name': '개인화 치수 데이터', 'verbose_name_plural': '개인화 치수 데이터'},
        ),
        migrations.AlterModelOptions(
            name='personalfituioption',
            options={'verbose_name': '개인화 치수 데이터 UI 옵션', 'verbose_name_plural': '개인화 치수 데이터 UI 옵션'},
        ),
        migrations.RemoveField(
            model_name='personalfituioption',
            name='button_group',
        ),
        migrations.AddField(
            model_name='personalfituioption',
            name='desc',
            field=models.CharField(help_text='그룹을 설명합니다.', max_length=60, null=True, verbose_name='그룹 설명'),
        ),
        migrations.AddField(
            model_name='personalfituioption',
            name='group',
            field=models.CharField(default='test', help_text='그룹으로 묶을 이름입니다.', max_length=20, verbose_name='그룹'),
            preserve_default=False,
        ),
    ]
